apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: ctse-lab-new
  name: ctse-lab-new
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ctse-lab-new
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ctse-lab-new
    spec:
      containers:
        - image: ashini98/ctse-lab12:c8b264ff5952200519069cb8deef49163c783e0c
          imagePullPolicy: Always
          name: ctse-lab12
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 3000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
