apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ctse-lab-newn
  name: ctse-lab-newn
spec:
  ports:
    - protocol: TCP
      port: 3000
  selector:
    app: ctse-lab-newn
  type: LoadBalancer
